In [52]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
bank_df = pd.read_csv("week5-Data/bank-sample.csv")

In [22]:
bank_df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,subscribed
0,31,management,single,tertiary,no,0,yes,no,cellular,15,apr,185,2,-1,0,unknown,no
1,45,entrepreneur,married,tertiary,no,1752,yes,yes,cellular,20,nov,56,2,-1,0,unknown,no
2,46,services,divorced,secondary,no,4329,no,no,cellular,21,nov,534,2,-1,0,unknown,yes
3,35,management,married,tertiary,no,1108,yes,no,cellular,17,nov,52,1,-1,0,unknown,no
4,39,management,married,secondary,no,1410,yes,no,unknown,23,may,55,1,-1,0,unknown,no

In [23]:
bank_df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000
mean,40.868000,1396.779500,15.82200,255.817000,2.655500,38.164000,0.530500
std,10.763527,3063.927783,8.29468,262.768065,3.055076,97.584817,1.810721
min,18.000000,-1854.000000,1.00000,5.000000,1.000000,-1.000000,0.000000
25%,32.000000,79.500000,8.00000,104.000000,1.000000,-1.000000,0.000000
50%,39.000000,463.500000,16.00000,178.000000,2.000000,-1.000000,0.000000
75%,49.000000,1407.750000,21.00000,309.000000,3.000000,-1.000000,0.000000
max,95.000000,36221.000000,31.00000,3881.000000,63.000000,674.000000,37.000000

In [24]:
bank_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         2000 non-null   int64
 1   job         2000 non-null   object
 2   marital     2000 non-null   object
 3   education   2000 non-null   object
 4   default     2000 non-null   object
 5   balance     2000 non-null   int64
 6   housing     2000 non-null   object
 7   loan        2000 non-null   object
 8   contact     2000 non-null   object
 9   day         2000 non-null   int64
 10  month       2000 non-null   object
 11  duration    2000 non-null   int64
 12  campaign    2000 non-null   int64
 13  pdays       2000 non-null   int64
 14  previous    2000 non-null   int64
 15  poutcome    2000 non-null   object
 16  subscribed  2000 non-null   object
dtypes: int64(7), object(10)
memory usage: 265.8+ KB

In [25]:
#selecting categorical columns

categorical_cols = bank_df.select_dtypes(include=['object']).columns

In [26]:
bank_df_encoded = bank_df.copy()

In [27]:
binary_cols = ['default', 'housing', 'loan', 'subscribed']
le = LabelEncoder()

for col in binary_cols:
    print(f"Encoding {col}: {bank_df_encoded[col].unique()}")
    bank_df_encoded[col] = le.fit_transform(bank_df_encoded[col])
    print(f"  -> Encoded values: {bank_df_encoded[col].unique()}")

Encoding default: ['no' 'yes']
  -> Encoded values: [0 1]
Encoding housing: ['yes' 'no']
  -> Encoded values: [1 0]
Encoding loan: ['no' 'yes']
  -> Encoded values: [0 1]
Encoding subscribed: ['no' 'yes']
  -> Encoded values: [0 1]

In [28]:
multi_class_cols = ['job', 'marital', 'education', 'contact', 'month', 'poutcome']

print(f"Original shape: {bank_df_encoded.shape}")

# Use pd.get_dummies for one-hot encoding (drop_first=True to avoid multicollinearity)
bank_df_encoded = pd.get_dummies(bank_df_encoded, columns=multi_class_cols, drop_first=True)

print(f"After one-hot encoding shape: {bank_df_encoded.shape}")
print(f"New columns created: {bank_df_encoded.shape[1] - bank_df.shape[1] + len(multi_class_cols)}")
print("\n")

Original shape: (2000, 17)
After one-hot encoding shape: (2000, 43)
New columns created: 32

In [29]:
print("Encoded DataFrame - First 5 Rows:")
print("=" * 50)
print(bank_df_encoded.head())
print("\n")

print("Encoded DataFrame Info:")
print("=" * 50)
bank_df_encoded.info()
print("\n")

print("Column names after encoding:")
print("=" * 50)
print(list(bank_df_encoded.columns))

Encoded DataFrame - First 5 Rows:
==================================================
   age  default  balance  housing  loan  day  duration  campaign  pdays  \
0   31        0        0        1     0   15       185         2     -1
1   45        0     1752        1     1   20        56         2     -1
2   46        0     4329        0     0   21       534         2     -1
3   35        0     1108        1     0   17        52         1     -1
4   39        0     1410        1     0   23        55         1     -1

   previous  ...  month_jul  month_jun  month_mar  month_may  month_nov  \
0         0  ...      False      False      False      False      False
1         0  ...      False      False      False      False       True
2         0  ...      False      False      False      False       True
3         0  ...      False      False      False      False       True
4         0  ...      False      False      False       True      False

   month_oct  month_sep  poutcome_other  poutcome_success  poutcome_unknown
0      False      False           False             False              True
1      False      False           False             False              True
2      False      False           False             False              True
3      False      False           False             False              True
4      False      False           False             False              True

[5 rows x 43 columns]


Encoded DataFrame Info:
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 43 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  2000 non-null   int64
 1   default              2000 non-null   int64
 2   balance              2000 non-null   int64
 3   housing              2000 non-null   int64
 4   loan                 2000 non-null   int64
 5   day                  2000 non-null   int64
 6   duration             2000 non-null   int64
 7   campaign             2000 non-null   int64
 8   pdays                2000 non-null   int64
 9   previous             2000 non-null   int64
 10  subscribed           2000 non-null   int64
 11  job_blue-collar      2000 non-null   bool
 12  job_entrepreneur     2000 non-null   bool
 13  job_housemaid        2000 non-null   bool
 14  job_management       2000 non-null   bool
 15  job_retired          2000 non-null   bool
 16  job_self-employed    2000 non-null   bool
 17  job_services         2000 non-null   bool
 18  job_student          2000 non-null   bool
 19  job_technician       2000 non-null   bool
 20  job_unemployed       2000 non-null   bool
 21  job_unknown          2000 non-null   bool
 22  marital_married      2000 non-null   bool
 23  marital_single       2000 non-null   bool
 24  education_secondary  2000 non-null   bool
 25  education_tertiary   2000 non-null   bool
 26  education_unknown    2000 non-null   bool
 27  contact_telephone    2000 non-null   bool
 28  contact_unknown      2000 non-null   bool
 29  month_aug            2000 non-null   bool
 30  month_dec            2000 non-null   bool
 31  month_feb            2000 non-null   bool
 32  month_jan            2000 non-null   bool
 33  month_jul            2000 non-null   bool
 34  month_jun            2000 non-null   bool
 35  month_mar            2000 non-null   bool
 36  month_may            2000 non-null   bool
 37  month_nov            2000 non-null   bool
 38  month_oct            2000 non-null   bool
 39  month_sep            2000 non-null   bool
 40  poutcome_other       2000 non-null   bool
 41  poutcome_success     2000 non-null   bool
 42  poutcome_unknown     2000 non-null   bool
dtypes: bool(32), int64(11)
memory usage: 234.5 KB


Column names after encoding:
==================================================
['age', 'default', 'balance', 'housing', 'loan', 'day', 'duration', 'campaign', 'pdays', 'previous', 'subscribed', 'job_blue-collar', 'job_entrepreneur', 'job_housemaid', 'job_management', 'job_retired', 'job_self-employed', 'job_services', 'job_student', 'job_technician', 'job_unemployed', 'job_unknown', 'marital_married', 'marital_single', 'education_secondary', 'education_tertiary', 'education_unknown', 'contact_telephone', 'contact_unknown', 'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul', 'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct', 'month_sep', 'poutcome_other', 'poutcome_success', 'poutcome_unknown']

In [30]:
X = bank_df_encoded.drop('subscribed', axis=1)
y = bank_df_encoded['subscribed']

In [31]:
from sklearn.model_selection import train_test_split
# Split data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y,
train_size=.7, random_state=3011)
# Check the splits are correct
print(f"Train size: {round(len(X_train) / len(X) * 100)}%")
print(f"Test size: {round(len(X_test) / len(X) * 100)}%")

Train size: 70%
Test size: 30%

In [32]:
# Identify numerical columns (excluding encoded categorical variables)
numerical_cols = ['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']
print("Numerical columns to scale:", numerical_cols)

Numerical columns to scale: ['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']

In [33]:
# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler ONLY on X_train and transform X_train
X_train_scaled = X_train.copy()
X_train_scaled[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])

# Transform X_test using the SAME scaler (do NOT fit again)
X_test_scaled = X_test.copy()
X_test_scaled[numerical_cols] = scaler.transform(X_test[numerical_cols])

print("Scaling complete!")
print(f"X_train_scaled shape: {X_train_scaled.shape}")
print(f"X_test_scaled shape: {X_test_scaled.shape}")

Scaling complete!
X_train_scaled shape: (1400, 42)
X_test_scaled shape: (600, 42)

In [35]:
from sklearn.linear_model import LogisticRegression

# Initialize the Logistic Regression model
log_reg = LogisticRegression(random_state=42, max_iter=1000)

# Fit the model on the scaled training data
log_reg.fit(X_train_scaled, y_train)

print("Logistic Regression model trained successfully!")

Logistic Regression model trained successfully!

In [36]:
# Make predictions on both train and test sets
y_train_pred = log_reg.predict(X_train_scaled)
y_test_pred = log_reg.predict(X_test_scaled)

print(f"Training predictions shape: {y_train_pred.shape}")
print(f"Test predictions shape: {y_test_pred.shape}")

Training predictions shape: (1400,)
Test predictions shape: (600,)

In [37]:
# Import metrics for evaluation
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Calculate accuracy
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

print(f"Training Accuracy: {train_accuracy:.4f} ({train_accuracy*100:.2f}%)")
print(f"Test Accuracy: {test_accuracy:.4f} ({test_accuracy*100:.2f}%)")

Training Accuracy: 0.9129 (91.29%)
Test Accuracy: 0.8883 (88.83%)

In [38]:
# Import SVM classifier
from sklearn.svm import SVC

In [39]:
# Initialize the SVM model with RBF kernel
svm_model = SVC(kernel='rbf', random_state=42)

# Fit the model on the scaled training data
svm_model.fit(X_train_scaled, y_train)

print("SVM model trained successfully!")

SVM model trained successfully!

In [40]:
# Make predictions on both train and test sets
y_train_pred_svm = svm_model.predict(X_train_scaled)
y_test_pred_svm = svm_model.predict(X_test_scaled)

print(f"Training predictions shape: {y_train_pred_svm.shape}")
print(f"Test predictions shape: {y_test_pred_svm.shape}")

Training predictions shape: (1400,)
Test predictions shape: (600,)

In [41]:
# Calculate accuracy
train_accuracy_svm = accuracy_score(y_train, y_train_pred_svm)
test_accuracy_svm = accuracy_score(y_test, y_test_pred_svm)

print(f"Training Accuracy: {train_accuracy_svm:.4f} ({train_accuracy_svm*100:.2f}%)")
print(f"Test Accuracy: {test_accuracy_svm:.4f} ({test_accuracy_svm*100:.2f}%)")

Training Accuracy: 0.9207 (92.07%)
Test Accuracy: 0.8833 (88.33%)

In [42]:
# Print detailed classification report for test set
print("Classification Report (Test Set) - SVM:")
print("="*60)
print(classification_report(y_test, y_test_pred_svm))

Classification Report (Test Set) - SVM:
============================================================
              precision    recall  f1-score   support

           0       0.89      0.99      0.94       529
           1       0.57      0.06      0.10        71

    accuracy                           0.88       600
   macro avg       0.73      0.53      0.52       600
weighted avg       0.85      0.88      0.84       600

In [43]:
# Display confusion matrix
print("Confusion Matrix (Test Set) - SVM:")
print("="*60)
cm_svm = confusion_matrix(y_test, y_test_pred_svm)
print(cm_svm)
print("\nInterpretation:")
print(f"True Negatives: {cm_svm[0,0]}")
print(f"False Positives: {cm_svm[0,1]}")
print(f"False Negatives: {cm_svm[1,0]}")
print(f"True Positives: {cm_svm[1,1]}")

Confusion Matrix (Test Set) - SVM:
============================================================
[[526   3]
 [ 67   4]]

Interpretation:
True Negatives: 526
False Positives: 3
False Negatives: 67
True Positives: 4

In [44]:
# Compare Logistic Regression vs SVM
print("Model Comparison:")
print("="*60)
print(f"Logistic Regression Test Accuracy: {test_accuracy:.4f} ({test_accuracy*100:.2f}%)")
print(f"SVM Test Accuracy: {test_accuracy_svm:.4f} ({test_accuracy_svm*100:.2f}%)")
print("\nDifference: {:.4f} ({:.2f}%)".format(
    abs(test_accuracy_svm - test_accuracy),
    abs(test_accuracy_svm - test_accuracy)*100
))

Model Comparison:
============================================================
Logistic Regression Test Accuracy: 0.8883 (88.83%)
SVM Test Accuracy: 0.8833 (88.33%)

Difference: 0.0050 (0.50%)

In [45]:
# Import Random Forest classifier
from sklearn.ensemble import RandomForestClassifier

In [46]:
# Initialize the Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the model on the scaled training data
rf_model.fit(X_train_scaled, y_train)

print("Random Forest model trained successfully!")

Random Forest model trained successfully!

In [47]:
# Make predictions on both train and test sets
y_train_pred_rf = rf_model.predict(X_train_scaled)
y_test_pred_rf = rf_model.predict(X_test_scaled)

print(f"Training predictions shape: {y_train_pred_rf.shape}")
print(f"Test predictions shape: {y_test_pred_rf.shape}")

Training predictions shape: (1400,)
Test predictions shape: (600,)

In [48]:
# Calculate accuracy
train_accuracy_rf = accuracy_score(y_train, y_train_pred_rf)
test_accuracy_rf = accuracy_score(y_test, y_test_pred_rf)

print(f"Training Accuracy: {train_accuracy_rf:.4f} ({train_accuracy_rf*100:.2f}%)")
print(f"Test Accuracy: {test_accuracy_rf:.4f} ({test_accuracy_rf*100:.2f}%)")

Training Accuracy: 1.0000 (100.00%)
Test Accuracy: 0.8983 (89.83%)

In [49]:
# Print detailed classification report for test set
print("Classification Report (Test Set) - Random Forest:")
print("="*60)
print(classification_report(y_test, y_test_pred_rf))

Classification Report (Test Set) - Random Forest:
============================================================
              precision    recall  f1-score   support

           0       0.90      1.00      0.95       529
           1       0.92      0.15      0.27        71

    accuracy                           0.90       600
   macro avg       0.91      0.58      0.61       600
weighted avg       0.90      0.90      0.86       600

In [50]:
# Display confusion matrix
print("Confusion Matrix (Test Set) - Random Forest:")
print("="*60)
cm_rf = confusion_matrix(y_test, y_test_pred_rf)
print(cm_rf)
print("\nInterpretation:")
print(f"True Negatives: {cm_rf[0,0]}")
print(f"False Positives: {cm_rf[0,1]}")
print(f"False Negatives: {cm_rf[1,0]}")
print(f"True Positives: {cm_rf[1,1]}")

Confusion Matrix (Test Set) - Random Forest:
============================================================
[[528   1]
 [ 60  11]]

Interpretation:
True Negatives: 528
False Positives: 1
False Negatives: 60
True Positives: 11

In [54]:
# Display feature importance from Random Forest
feature_importance = pd.DataFrame({
    'feature': X_train_scaled.columns,
    'importance': rf_model.feature_importances_
}).sort_values('importance', ascending=False)

print("Top 10 Most Important Features:")
print("="*60)
print(feature_importance.head(10))

Top 10 Most Important Features:
============================================================
             feature  importance
6           duration    0.231813
2            balance    0.098452
0                age    0.089134
5                day    0.079302
8              pdays    0.040065
7           campaign    0.039702
40  poutcome_success    0.028548
9           previous    0.025911
3            housing    0.025273
29         month_dec    0.020659

In [55]:
# Compare all three models
print("Model Comparison Summary:")
print("="*60)
models_comparison = pd.DataFrame({
    'Model': ['Logistic Regression', 'SVM', 'Random Forest'],
    'Train Accuracy': [train_accuracy, train_accuracy_svm, train_accuracy_rf],
    'Test Accuracy': [test_accuracy, test_accuracy_svm, test_accuracy_rf]
})
print(models_comparison)
print("\nBest Model (Test Accuracy):", 
      models_comparison.loc[models_comparison['Test Accuracy'].idxmax(), 'Model'])

Model Comparison Summary:
============================================================
                 Model  Train Accuracy  Test Accuracy
0  Logistic Regression        0.912857       0.888333
1                  SVM        0.920714       0.883333
2        Random Forest        1.000000       0.898333

Best Model (Test Accuracy): Random Forest

In [56]:
!pip install xgboost

Collecting xgboost
  Using cached xgboost-3.1.2-py3-none-macosx_12_0_arm64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in ./.venv/lib/python3.12/site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in ./.venv/lib/python3.12/site-packages (from xgboost) (1.16.3)
Using cached xgboost-3.1.2-py3-none-macosx_12_0_arm64.whl (2.2 MB)
Installing collected packages: xgboost
Successfully installed xgboost-3.1.2

In [57]:
# Import XGBoost classifier
from xgboost import XGBClassifier

In [58]:
# Initialize the XGBoost model
xgb_model = XGBClassifier(n_estimators=100, random_state=42, eval_metric='logloss')

# Fit the model on the scaled training data
xgb_model.fit(X_train_scaled, y_train)

print("XGBoost model trained successfully!")

XGBoost model trained successfully!

In [59]:
# Make predictions on both train and test sets
y_train_pred_xgb = xgb_model.predict(X_train_scaled)
y_test_pred_xgb = xgb_model.predict(X_test_scaled)

print(f"Training predictions shape: {y_train_pred_xgb.shape}")
print(f"Test predictions shape: {y_test_pred_xgb.shape}")

Training predictions shape: (1400,)
Test predictions shape: (600,)

In [60]:
# Calculate accuracy
train_accuracy_xgb = accuracy_score(y_train, y_train_pred_xgb)
test_accuracy_xgb = accuracy_score(y_test, y_test_pred_xgb)

print(f"Training Accuracy: {train_accuracy_xgb:.4f} ({train_accuracy_xgb*100:.2f}%)")
print(f"Test Accuracy: {test_accuracy_xgb:.4f} ({test_accuracy_xgb*100:.2f}%)")

Training Accuracy: 1.0000 (100.00%)
Test Accuracy: 0.8983 (89.83%)

In [61]:
# Print detailed classification report for test set
print("Classification Report (Test Set) - XGBoost:")
print("="*60)
print(classification_report(y_test, y_test_pred_xgb))

Classification Report (Test Set) - XGBoost:
============================================================
              precision    recall  f1-score   support

           0       0.91      0.98      0.94       529
           1       0.64      0.32      0.43        71

    accuracy                           0.90       600
   macro avg       0.78      0.65      0.69       600
weighted avg       0.88      0.90      0.88       600

In [62]:
# Display confusion matrix
print("Confusion Matrix (Test Set) - XGBoost:")
print("="*60)
cm_xgb = confusion_matrix(y_test, y_test_pred_xgb)
print(cm_xgb)
print("\nInterpretation:")
print(f"True Negatives: {cm_xgb[0,0]}")
print(f"False Positives: {cm_xgb[0,1]}")
print(f"False Negatives: {cm_xgb[1,0]}")
print(f"True Positives: {cm_xgb[1,1]}")

Confusion Matrix (Test Set) - XGBoost:
============================================================
[[516  13]
 [ 48  23]]

Interpretation:
True Negatives: 516
False Positives: 13
False Negatives: 48
True Positives: 23

In [63]:
# Display feature importance from XGBoost
feature_importance_xgb = pd.DataFrame({
    'feature': X_train_scaled.columns,
    'importance': xgb_model.feature_importances_
}).sort_values('importance', ascending=False)

print("Top 10 Most Important Features (XGBoost):")
print("="*60)
print(feature_importance_xgb.head(10))

Top 10 Most Important Features (XGBoost):
============================================================
             feature  importance
40  poutcome_success    0.079941
37         month_oct    0.072985
3            housing    0.048701
36         month_nov    0.044033
6           duration    0.043818
29         month_dec    0.041812
19    job_unemployed    0.041740
9           previous    0.035695
34         month_mar    0.034802
12     job_housemaid    0.033841

In [64]:
# Compare all four models
print("Model Comparison Summary:")
print("="*60)
models_comparison = pd.DataFrame({
    'Model': ['Logistic Regression', 'SVM', 'Random Forest', 'XGBoost'],
    'Train Accuracy': [train_accuracy, train_accuracy_svm, train_accuracy_rf, train_accuracy_xgb],
    'Test Accuracy': [test_accuracy, test_accuracy_svm, test_accuracy_rf, test_accuracy_xgb]
})
models_comparison['Overfitting'] = models_comparison['Train Accuracy'] - models_comparison['Test Accuracy']
print(models_comparison)
print("\nBest Model (Test Accuracy):", 
      models_comparison.loc[models_comparison['Test Accuracy'].idxmax(), 'Model'])

Model Comparison Summary:
============================================================
                 Model  Train Accuracy  Test Accuracy  Overfitting
0  Logistic Regression        0.912857       0.888333     0.024524
1                  SVM        0.920714       0.883333     0.037381
2        Random Forest        1.000000       0.898333     0.101667
3              XGBoost        1.000000       0.898333     0.101667

Best Model (Test Accuracy): Random Forest

In [65]:
# Import GridSearchCV for hyperparameter tuning
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [66]:
# Define hyperparameter grid for XGBoost
xgb_param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7, 10],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'subsample': [0.8, 0.9, 1.0],
    'colsample_bytree': [0.8, 0.9, 1.0]
}

# Use RandomizedSearchCV for faster tuning
xgb_tuned = RandomizedSearchCV(
    XGBClassifier(random_state=42, eval_metric='logloss'),
    xgb_param_grid,
    n_iter=50,
    cv=5,
    scoring='accuracy',
    random_state=42,
    n_jobs=-1
)

xgb_tuned.fit(X_train_scaled, y_train)

print("Best XGBoost Parameters:")
print(xgb_tuned.best_params_)
print(f"\nBest CV Accuracy: {xgb_tuned.best_score_:.4f}")

Best XGBoost Parameters:
{'subsample': 0.8, 'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.05, 'colsample_bytree': 0.9}

Best CV Accuracy: 0.9014

In [67]:
# Evaluate tuned XGBoost model
y_test_pred_xgb_tuned = xgb_tuned.predict(X_test_scaled)
test_accuracy_xgb_tuned = accuracy_score(y_test, y_test_pred_xgb_tuned)

print(f"Tuned XGBoost Test Accuracy: {test_accuracy_xgb_tuned:.4f} ({test_accuracy_xgb_tuned*100:.2f}%)")
print(f"Improvement: {(test_accuracy_xgb_tuned - test_accuracy_xgb)*100:.2f}%")
print("\nClassification Report:")
print(classification_report(y_test, y_test_pred_xgb_tuned))

Tuned XGBoost Test Accuracy: 0.8967 (89.67%)
Improvement: -0.17%

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.98      0.94       529
           1       0.68      0.24      0.35        71

    accuracy                           0.90       600
   macro avg       0.79      0.61      0.65       600
weighted avg       0.88      0.90      0.87       600

In [68]:
# Define hyperparameter grid for Random Forest
rf_param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']
}

rf_tuned = RandomizedSearchCV(
    RandomForestClassifier(random_state=42),
    rf_param_grid,
    n_iter=50,
    cv=5,
    scoring='accuracy',
    random_state=42,
    n_jobs=-1
)

rf_tuned.fit(X_train_scaled, y_train)

print("Best Random Forest Parameters:")
print(rf_tuned.best_params_)
print(f"\nBest CV Accuracy: {rf_tuned.best_score_:.4f}")

Best Random Forest Parameters:
{'n_estimators': 100, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'max_depth': 20}

Best CV Accuracy: 0.9043

In [69]:
# Gradient Boosting Classifier
from sklearn.ensemble import GradientBoostingClassifier

gb_model = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=5,
    random_state=42
)

gb_model.fit(X_train_scaled, y_train)
y_test_pred_gb = gb_model.predict(X_test_scaled)
test_accuracy_gb = accuracy_score(y_test, y_test_pred_gb)

print(f"Gradient Boosting Test Accuracy: {test_accuracy_gb:.4f} ({test_accuracy_gb*100:.2f}%)")
print(classification_report(y_test, y_test_pred_gb))

Gradient Boosting Test Accuracy: 0.8783 (87.83%)
              precision    recall  f1-score   support

           0       0.90      0.97      0.93       529
           1       0.47      0.20      0.28        71

    accuracy                           0.88       600
   macro avg       0.68      0.58      0.61       600
weighted avg       0.85      0.88      0.86       600

In [71]:
!pip install lightgbm

Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-macosx_12_0_arm64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.17.0 in ./.venv/lib/python3.12/site-packages (from lightgbm) (1.26.4)
Requirement already satisfied: scipy in ./.venv/lib/python3.12/site-packages (from lightgbm) (1.16.3)
Downloading lightgbm-4.6.0-py3-none-macosx_12_0_arm64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 197.0 kB/s  0:00:07 eta 0:00:02
Installing collected packages: lightgbm
Successfully installed lightgbm-4.6.0

In [72]:
# Install if needed: !pip install lightgbm
from lightgbm import LGBMClassifier

lgbm_model = LGBMClassifier(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=10,
    random_state=42,
    verbose=-1
)

lgbm_model.fit(X_train_scaled, y_train)
y_test_pred_lgbm = lgbm_model.predict(X_test_scaled)
test_accuracy_lgbm = accuracy_score(y_test, y_test_pred_lgbm)

print(f"LightGBM Test Accuracy: {test_accuracy_lgbm:.4f} ({test_accuracy_lgbm*100:.2f}%)")
print(classification_report(y_test, y_test_pred_lgbm))

LightGBM Test Accuracy: 0.8950 (89.50%)
              precision    recall  f1-score   support

           0       0.91      0.97      0.94       529
           1       0.61      0.31      0.41        71

    accuracy                           0.90       600
   macro avg       0.76      0.64      0.68       600
weighted avg       0.88      0.90      0.88       600

In [73]:
# Ensemble: Combine the best models
from sklearn.ensemble import VotingClassifier

# Create voting classifier with soft voting
voting_model = VotingClassifier(
    estimators=[
        ('xgb', XGBClassifier(n_estimators=200, random_state=42, eval_metric='logloss')),
        ('rf', RandomForestClassifier(n_estimators=200, random_state=42)),
        ('lgbm', LGBMClassifier(n_estimators=200, random_state=42, verbose=-1))
    ],
    voting='soft'
)

voting_model.fit(X_train_scaled, y_train)
y_test_pred_voting = voting_model.predict(X_test_scaled)
test_accuracy_voting = accuracy_score(y_test, y_test_pred_voting)

print(f"Voting Ensemble Test Accuracy: {test_accuracy_voting:.4f} ({test_accuracy_voting*100:.2f}%)")
print(classification_report(y_test, y_test_pred_voting))

Voting Ensemble Test Accuracy: 0.8883 (88.83%)
              precision    recall  f1-score   support

           0       0.91      0.97      0.94       529
           1       0.56      0.25      0.35        71

    accuracy                           0.89       600
   macro avg       0.73      0.61      0.64       600
weighted avg       0.87      0.89      0.87       600

In [74]:
# Check class distribution
print("Class Distribution:")
print(y_train.value_counts())
print(f"\nClass Ratio: {y_train.value_counts()[0] / y_train.value_counts()[1]:.2f}:1")

Class Distribution:
subscribed
0    1260
1     140
Name: count, dtype: int64

Class Ratio: 9.00:1

In [75]:
!pip install imbalanced-learn

Collecting imbalanced-learn
  Downloading imbalanced_learn-0.14.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in ./.venv/lib/python3.12/site-packages (from imbalanced-learn) (1.26.4)
Requirement already satisfied: scipy<2,>=1.11.4 in ./.venv/lib/python3.12/site-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in ./.venv/lib/python3.12/site-packages (from imbalanced-learn) (1.8.0)
Collecting sklearn-compat<0.2,>=0.1.5 (from imbalanced-learn)
  Downloading sklearn_compat-0.1.5-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: joblib<2,>=1.2.0 in ./.venv/lib/python3.12/site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in ./.venv/lib/python3.12/site-packages (from imbalanced-learn) (3.6.0)
Downloading imbalanced_learn-0.14.1-py3-none-any.whl (235 kB)
Downloading sklearn_compat-0.1.5-py3-none-any.whl (20 kB)
Installing collected packages: sklearn-compat, imbalanced-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [imbalanced-learn]
Successfully installed imbalanced-learn-0.14.1 sklearn-compat-0.1.5

In [76]:
# Install if needed: !pip install imbalanced-learn
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train_scaled, y_train)

print(f"Before SMOTE: {y_train.value_counts().to_dict()}")
print(f"After SMOTE: {pd.Series(y_train_smote).value_counts().to_dict()}")

# Train XGBoost on balanced data
xgb_smote = XGBClassifier(n_estimators=200, random_state=42, eval_metric='logloss')
xgb_smote.fit(X_train_smote, y_train_smote)

y_test_pred_smote = xgb_smote.predict(X_test_scaled)
test_accuracy_smote = accuracy_score(y_test, y_test_pred_smote)

print(f"\nXGBoost + SMOTE Test Accuracy: {test_accuracy_smote:.4f}")
print(classification_report(y_test, y_test_pred_smote))

Before SMOTE: {0: 1260, 1: 140}
After SMOTE: {0: 1260, 1: 1260}

XGBoost + SMOTE Test Accuracy: 0.8783
              precision    recall  f1-score   support

           0       0.91      0.95      0.93       529
           1       0.48      0.32      0.39        71

    accuracy                           0.88       600
   macro avg       0.70      0.64      0.66       600
weighted avg       0.86      0.88      0.87       600

In [77]:
# Compare all models
all_models = pd.DataFrame({
    'Model': ['Logistic Regression', 'SVM', 'Random Forest', 'XGBoost', 
              'Tuned XGBoost', 'Gradient Boosting', 'LightGBM', 'Voting Ensemble'],
    'Test Accuracy': [test_accuracy, test_accuracy_svm, test_accuracy_rf, test_accuracy_xgb,
                      test_accuracy_xgb_tuned, test_accuracy_gb, test_accuracy_lgbm, test_accuracy_voting]
}).sort_values('Test Accuracy', ascending=False)

print("Final Model Comparison:")
print("="*60)
print(all_models)
print(f"\n🏆 Best Model: {all_models.iloc[0]['Model']} with {all_models.iloc[0]['Test Accuracy']:.4f} accuracy")

Final Model Comparison:
============================================================
                 Model  Test Accuracy
2        Random Forest       0.898333
3              XGBoost       0.898333
4        Tuned XGBoost       0.896667
6             LightGBM       0.895000
0  Logistic Regression       0.888333
7      Voting Ensemble       0.888333
1                  SVM       0.883333
5    Gradient Boosting       0.878333

🏆 Best Model: Random Forest with 0.8983 accuracy